snapshot of project "autoconf-252", label t20100930

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20100814 for GNU Autoconf 2.52.20100928.
+# Generated by Autoconf 2.52.20100930 for GNU Autoconf 2.52.20100930.
 #
 # Report bugs to <dickey@invisible-island.net>.
 #
@@ -149,8 +149,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52.20100928'
-PACKAGE_STRING='GNU Autoconf 2.52.20100928'
+PACKAGE_VERSION='2.52.20100930'
+PACKAGE_STRING='GNU Autoconf 2.52.20100930'
 PACKAGE_BUGREPORT='dickey@invisible-island.net'
 
 ac_prev=
@@ -547,7 +547,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.52.20100928 to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52.20100930 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -609,7 +609,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20100928:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20100930:";;
    esac
   cat <<\EOF
 
@@ -656,8 +656,8 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.52.20100928
-generated by GNU Autoconf 2.52.20100814
+GNU Autoconf configure 2.52.20100930
+generated by GNU Autoconf 2.52.20100930
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 Free Software Foundation, Inc.
@@ -671,8 +671,8 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52.20100928, which was
-generated by GNU Autoconf 2.52.20100814.  Invocation command line was
+It was created by GNU Autoconf $as_me 2.52.20100930, which was
+generated by GNU Autoconf 2.52.20100930.  Invocation command line was
 
   $ $0 $@
 
@@ -1097,7 +1097,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.52.20100928
+VERSION=2.52.20100930
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1103: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1114,14 +1114,26 @@ cat >>confdefs.h <<EOF
 EOF
 
 missing_dir=`cd $ac_aux_dir && pwd`
+#
+ac_prog_editor=`echo $program_transform_name| sed -e 's/\\$\\$/$/g'`
+ac_prog_actual=`echo aclocal|sed -e $ac_prog_editor`
 
-ACLOCAL=${ACLOCAL-"${am_missing_run}aclocal"}
+ACLOCAL=${ACLOCAL-"${am_missing_run}$ac_prog_actual"}
 
-AUTOCONF=${AUTOCONF-"${am_missing_run}autoconf"}
+#
+ac_prog_actual=`echo autoconf|sed -e $ac_prog_editor`
 
+AUTOCONF=${AUTOCONF-"${am_missing_run}$ac_prog_actual"}
+
+#
 AUTOMAKE=${AUTOMAKE-"automake"}
 
-AUTOHEADER=${AUTOHEADER-"${am_missing_run}autoheader"}
+#
+ac_prog_actual=`echo autoheader|sed -e $ac_prog_editor`
+
+AUTOHEADER=${AUTOHEADER-"${am_missing_run}$ac_prog_actual"}
+
+#
 
 MAKEINFO=${MAKEINFO-"${am_missing_run}makeinfo"}
 
@@ -1130,7 +1142,7 @@ AUTOTEST_PATH=..
 
 # Extract the first word of "expr", so it can be a program name with args.
 set dummy expr; ac_word=$2
-echo "$as_me:1133: checking for $ac_word" >&5
+echo "$as_me:1145: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_EXPR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1147,7 +1159,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_EXPR="$ac_dir/$ac_word"
-   echo "$as_me:1150: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1162: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1158,10 +1170,10 @@ fi
 EXPR=$ac_cv_path_EXPR
 
 if test -n "$EXPR"; then
-  echo "$as_me:1161: result: $EXPR" >&5
+  echo "$as_me:1173: result: $EXPR" >&5
 echo "${ECHO_T}$EXPR" >&6
 else
-  echo "$as_me:1164: result: no" >&5
+  echo "$as_me:1176: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1173,7 +1185,7 @@ for ac_prog in gm4 gnum4 m4
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1176: checking for $ac_word" >&5
+echo "$as_me:1188: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_M4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1190,7 +1202,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_M4="$ac_dir/$ac_word"
-   echo "$as_me:1193: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1205: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1201,10 +1213,10 @@ fi
 M4=$ac_cv_path_M4
 
 if test -n "$M4"; then
-  echo "$as_me:1204: result: $M4" >&5
+  echo "$as_me:1216: result: $M4" >&5
 echo "${ECHO_T}$M4" >&6
 else
-  echo "$as_me:1207: result: no" >&5
+  echo "$as_me:1219: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1212,7 +1224,7 @@ fi
 done
 test -n "$M4" || M4="m4"
 
-echo "$as_me:1215: checking whether m4 supports frozen files" >&5
+echo "$as_me:1227: checking whether m4 supports frozen files" >&5
 echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1224,10 +1236,10 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "$as_me:1227: result: $ac_cv_prog_gnu_m4" >&5
+echo "$as_me:1239: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { { echo "$as_me:1230: error: GNU m4 1.4 is required" >&5
+  { { echo "$as_me:1242: error: GNU m4 1.4 is required" >&5
 echo "$as_me: error: GNU m4 1.4 is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1239,7 +1251,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1242: checking for $ac_word" >&5
+echo "$as_me:1254: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1254,7 +1266,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_AWK="$ac_prog"
-echo "$as_me:1257: found $ac_dir/$ac_word" >&5
+echo "$as_me:1269: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1262,10 +1274,10 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1265: result: $AWK" >&5
+  echo "$as_me:1277: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1268: result: no" >&5
+  echo "$as_me:1280: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1274,7 +1286,7 @@ done
 
 # Some AWK fail
 if echo xfoo | $AWK '/foo|^bar$/ { print }' | grep xfoo >/dev/null; then :; else
-  { { echo "$as_me:1277: error: the regex engine of $AWK is too broken to be used
+  { { echo "$as_me:1289: error: the regex engine of $AWK is too broken to be used
                 you might want to install GNU AWK" >&5
 echo "$as_me: error: the regex engine of $AWK is too broken to be used
                 you might want to install GNU AWK" >&2;}
@@ -1288,7 +1300,7 @@ HELP2MAN=${HELP2MAN-"${am_missing_run}help2man"}
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1291: checking for $ac_word" >&5
+echo "$as_me:1303: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1305,7 +1317,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PERL="$ac_dir/$ac_word"
-   echo "$as_me:1308: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1320: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1317,17 +1329,17 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1320: result: $PERL" >&5
+  echo "$as_me:1332: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1323: result: no" >&5
+  echo "$as_me:1335: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" != no; then
   PERLSCRIPTS="autoscan autoupdate"
 else
-  { echo "$as_me:1330: WARNING: autoscan and autoupdate will not be built since perl is not found" >&5
+  { echo "$as_me:1342: WARNING: autoscan and autoupdate will not be built since perl is not found" >&5
 echo "$as_me: WARNING: autoscan and autoupdate will not be built since perl is not found" >&2;}
 fi
 
@@ -1343,7 +1355,7 @@ fi
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "$as_me:1346: checking for a BSD compatible install" >&5
+echo "$as_me:1358: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1392,7 +1404,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "$as_me:1395: result: $INSTALL" >&5
+echo "$as_me:1407: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -1402,6 +1414,55 @@ test -z "$INSTALL_PROGRAM" && INSTALL_PROGRAM='${INSTALL}'
 test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
+
+for ac_prog in ginstall-info install-info
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:1422: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_INSTALL_INFO+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$INSTALL_INFO"; then
+  ac_cv_prog_INSTALL_INFO="$INSTALL_INFO" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_INSTALL_INFO="$ac_prog"
+echo "$as_me:1437: found $ac_dir/$ac_word" >&5
+break
+done
+
+fi
+fi
+INSTALL_INFO=$ac_cv_prog_INSTALL_INFO
+if test -n "$INSTALL_INFO"; then
+  echo "$as_me:1445: result: $INSTALL_INFO" >&5
+echo "${ECHO_T}$INSTALL_INFO" >&6
+else
+  echo "$as_me:1448: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$INSTALL_INFO" && break
+done
+test -n "$INSTALL_INFO" || INSTALL_INFO="no"
+
+if test "$INSTALL_INFO" != no; then
+  if $INSTALL_INFO --version && \
+	 ( $INSTALL_INFO --version | fgrep -i -v debian ) >/dev/null 2>&1; then
+     :
+  else
+    { echo "$as_me:1461: WARNING: install-info utility not found" >&5
+echo "$as_me: WARNING: install-info utility not found" >&2;}
+	INSTALL_INFO=no
+  fi
+fi
 
 # Automake can't see inner AC_SUBSTS (`aclocal' is bypassed), so we tag the
 # AC_SUBSTS here too.
@@ -1517,7 +1578,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1520: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1581: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1635,13 +1696,13 @@ Usage: $0 [OPTIONS] [FILE]...
 Configuration files:
 $config_files
 
-Report bugs to <bug-autoconf@gnu.org>."
+Report bugs to <dickey@invisible-island.net>."
 EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52.20100928
-configured by $0, generated by GNU Autoconf 2.52.20100814,
+GNU Autoconf config.status 2.52.20100930
+configured by $0, generated by GNU Autoconf 2.52.20100930,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -1685,7 +1746,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1688: error: ambiguous option: $1
+    { { echo "$as_me:1749: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1704,7 +1765,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1707: error: unrecognized option: $1
+  -*) { { echo "$as_me:1768: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1723,7 +1784,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.52.20100928) 2.52.20100814, executed with
+This file was extended by $as_me (GNU Autoconf 2.52.20100930) 2.52.20100930, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1746,7 +1807,7 @@ do
   "config/Makefile" ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-  *) { { echo "$as_me:1749: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1810: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1844,6 +1905,7 @@ s,@AWK@,$AWK,;t t
 s,@HELP2MAN@,$HELP2MAN,;t t
 s,@PERL@,$PERL,;t t
 s,@PERLSCRIPTS@,$PERLSCRIPTS,;t t
+s,@INSTALL_INFO@,$INSTALL_INFO,;t t
 CEOF
 
 EOF
@@ -1958,7 +2020,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1961: creating $ac_file" >&5
+    { echo "$as_me:2023: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1976,7 +2038,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1979: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2041: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1989,7 +2051,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1992: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2054: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2045,7 +2107,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.52.20100928 in
+case 2.52.20100930 in
   *[a-z]*)
     cat <<EOF
 
