snapshot of project "autoconf-252", label t20200111

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20190901 for GNU Autoconf 2.52.20190901.
+# Generated by Autoconf 2.52.20200111 for GNU Autoconf 2.52.20200111.
 #
 # Report bugs to <dickey@invisible-island.net>.
 #
@@ -151,8 +151,8 @@ mandir='${datarootdir}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52.20190901'
-PACKAGE_STRING='GNU Autoconf 2.52.20190901'
+PACKAGE_VERSION='2.52.20200111'
+PACKAGE_STRING='GNU Autoconf 2.52.20200111'
 PACKAGE_BUGREPORT='dickey@invisible-island.net'
 
 ac_prev=
@@ -565,7 +565,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.52.20190901 to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52.20200111 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -629,7 +629,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20190901:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20200111:";;
    esac
   cat <<\EOF
 
@@ -676,8 +676,8 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.52.20190901
-generated by GNU Autoconf 2.52.20190901
+GNU Autoconf configure 2.52.20200111
+generated by GNU Autoconf 2.52.20200111
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 Free Software Foundation, Inc.
@@ -691,8 +691,8 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52.20190901, which was
-generated by GNU Autoconf 2.52.20190901.  Invocation command line was
+It was created by GNU Autoconf $as_me 2.52.20200111, which was
+generated by GNU Autoconf 2.52.20200111.  Invocation command line was
 
   $ $0 $@
 
@@ -1117,7 +1117,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.52.20190901
+VERSION=2.52.20200111
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1123: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1244,8 +1244,20 @@ fi
 done
 test -n "$M4" || M4="m4"
 
-echo "$as_me:1247: checking whether m4 supports frozen files" >&5
-echo $ECHO_N "checking whether m4 supports frozen files... $ECHO_C" >&6
+echo "$as_me:1247: checking version of $M4" >&5
+echo $ECHO_N "checking version of $M4... $ECHO_C" >&6
+if test "${ac_cv_m4_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	ac_cv_m4_version=`$M4 --version | head -n 1 | sed -E -e 's/^.*[ ]([1-9][0-9]*\.)/\1/g' -e 's/[^0-9.]*$//' 2>/dev/null`
+	test -z "$ac_cv_m4_version" && ac_cv_m4_version=unknown
+
+fi
+echo "$as_me:1257: result: $ac_cv_m4_version" >&5
+echo "${ECHO_T}$ac_cv_m4_version" >&6
+echo "$as_me:1259: checking whether $M4 supports frozen files" >&5
+echo $ECHO_N "checking whether $M4 supports frozen files... $ECHO_C" >&6
 if test "${ac_cv_prog_gnu_m4+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -1256,10 +1268,10 @@ if test x"$M4" != x; then
   esac
 fi
 fi
-echo "$as_me:1259: result: $ac_cv_prog_gnu_m4" >&5
+echo "$as_me:1271: result: $ac_cv_prog_gnu_m4" >&5
 echo "${ECHO_T}$ac_cv_prog_gnu_m4" >&6
 if test x"$ac_cv_prog_gnu_m4" != xyes; then
-  { { echo "$as_me:1262: error: GNU m4 1.4 is required" >&5
+  { { echo "$as_me:1274: error: GNU m4 1.4 is required" >&5
 echo "$as_me: error: GNU m4 1.4 is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1271,7 +1283,7 @@ for ac_prog in mawk gawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1274: checking for $ac_word" >&5
+echo "$as_me:1286: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_AWK+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1286,7 +1298,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_AWK="$ac_prog"
-echo "$as_me:1289: found $ac_dir/$ac_word" >&5
+echo "$as_me:1301: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1294,10 +1306,10 @@ fi
 fi
 AWK=$ac_cv_prog_AWK
 if test -n "$AWK"; then
-  echo "$as_me:1297: result: $AWK" >&5
+  echo "$as_me:1309: result: $AWK" >&5
 echo "${ECHO_T}$AWK" >&6
 else
-  echo "$as_me:1300: result: no" >&5
+  echo "$as_me:1312: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1306,7 +1318,7 @@ done
 
 # Some AWK fail
 if echo xfoo | $AWK '/foo|^bar$/ { print }' | grep xfoo >/dev/null; then :; else
-  { { echo "$as_me:1309: error: the regex engine of $AWK is too broken to be used
+  { { echo "$as_me:1321: error: the regex engine of $AWK is too broken to be used
                 you might want to install GNU AWK" >&5
 echo "$as_me: error: the regex engine of $AWK is too broken to be used
                 you might want to install GNU AWK" >&2;}
@@ -1320,7 +1332,7 @@ HELP2MAN=${HELP2MAN-"${am_missing_run}help2man"}
 # We use a path for perl so the #! line in autoscan will work.
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
-echo "$as_me:1323: checking for $ac_word" >&5
+echo "$as_me:1335: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1337,7 +1349,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_PERL="$ac_dir/$ac_word"
-   echo "$as_me:1340: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1352: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1349,17 +1361,17 @@ fi
 PERL=$ac_cv_path_PERL
 
 if test -n "$PERL"; then
-  echo "$as_me:1352: result: $PERL" >&5
+  echo "$as_me:1364: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:1355: result: no" >&5
+  echo "$as_me:1367: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$PERL" != no; then
   PERLSCRIPTS="autoscan autoupdate"
 else
-  { echo "$as_me:1362: WARNING: autoscan and autoupdate will not be built since perl is not found" >&5
+  { echo "$as_me:1374: WARNING: autoscan and autoupdate will not be built since perl is not found" >&5
 echo "$as_me: WARNING: autoscan and autoupdate will not be built since perl is not found" >&2;}
 fi
 
@@ -1375,7 +1387,7 @@ fi
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "$as_me:1378: checking for a BSD compatible install" >&5
+echo "$as_me:1390: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1424,7 +1436,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "$as_me:1427: result: $INSTALL" >&5
+echo "$as_me:1439: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -1439,7 +1451,7 @@ for ac_prog in ginstall-info install-info
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1442: checking for $ac_word" >&5
+echo "$as_me:1454: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_INSTALL_INFO+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1456,7 +1468,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_INSTALL_INFO="$ac_dir/$ac_word"
-   echo "$as_me:1459: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1471: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1467,10 +1479,10 @@ fi
 INSTALL_INFO=$ac_cv_path_INSTALL_INFO
 
 if test -n "$INSTALL_INFO"; then
-  echo "$as_me:1470: result: $INSTALL_INFO" >&5
+  echo "$as_me:1482: result: $INSTALL_INFO" >&5
 echo "${ECHO_T}$INSTALL_INFO" >&6
 else
-  echo "$as_me:1473: result: no" >&5
+  echo "$as_me:1485: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1483,7 +1495,7 @@ if test "$INSTALL_INFO" != no; then
 	 ( $INSTALL_INFO --version | fgrep -i -v debian ) >/dev/null 2>&1; then
      :
   else
-    { echo "$as_me:1486: WARNING: install-info utility not found" >&5
+    { echo "$as_me:1498: WARNING: install-info utility not found" >&5
 echo "$as_me: WARNING: install-info utility not found" >&2;}
 	INSTALL_INFO=no
   fi
@@ -1606,7 +1618,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1609: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1621: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1729,8 +1741,8 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52.20190901
-configured by $0, generated by GNU Autoconf 2.52.20190901,
+GNU Autoconf config.status 2.52.20200111
+configured by $0, generated by GNU Autoconf 2.52.20200111,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -1774,7 +1786,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1777: error: ambiguous option: $1
+    { { echo "$as_me:1789: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1793,7 +1805,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1796: error: unrecognized option: $1
+  -*) { { echo "$as_me:1808: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1812,7 +1824,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.52.20190901) 2.52.20190901, executed with
+This file was extended by $as_me (GNU Autoconf 2.52.20200111) 2.52.20200111, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1835,7 +1847,7 @@ do
   "config/Makefile" ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-  *) { { echo "$as_me:1838: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1850: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2069,7 +2081,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2072: creating $ac_file" >&5
+    { echo "$as_me:2084: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2087,7 +2099,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2090: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2102: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2100,7 +2112,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2103: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2115: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2116,7 +2128,7 @@ cat >>$CONFIG_STATUS <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' $ac_item`
         if test -z "$ac_used"; then
-          { echo "$as_me:2119: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:2131: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -2125,7 +2137,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' $ac_item`
       if test -n "$ac_seen"; then
-        { echo "$as_me:2128: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:2140: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -2162,7 +2174,7 @@ s,@INSTALL@,$ac_INSTALL,;t t
             ac_init=`egrep '[ 	]*'$ac_name'[ 	]*=' $ac_file`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'$ac_file':,'`
-              { echo "$as_me:2165: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:2177: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -2173,7 +2185,7 @@ $ac_seen" >&2;}
     egrep -n '@[A-Z_][A-Z_0-9]+@' $ac_file >>$tmp/out
     if test -s $tmp/out; then
       ac_seen=`sed -e 's,^,'$ac_file':,' < $tmp/out`
-      { echo "$as_me:2176: WARNING: Some variables may not be substituted:
+      { echo "$as_me:2188: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -2212,7 +2224,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.52.20190901 in
+case 2.52.20200111 in
   *[a-z]*)
     cat <<EOF
 
