snapshot of project "autoconf-252", label t20150926

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20141204 for GNU Autoconf 2.52.20141204.
+# Generated by Autoconf 2.52.20150926 for GNU Autoconf 2.52.20150926.
 #
 # Report bugs to <dickey@invisible-island.net>.
 #
@@ -150,8 +150,8 @@ mandir='${datarootdir}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52.20141204'
-PACKAGE_STRING='GNU Autoconf 2.52.20141204'
+PACKAGE_VERSION='2.52.20150926'
+PACKAGE_STRING='GNU Autoconf 2.52.20150926'
 PACKAGE_BUGREPORT='dickey@invisible-island.net'
 
 ac_prev=
@@ -555,7 +555,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.52.20141204 to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52.20150926 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -618,7 +618,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20141204:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20150926:";;
    esac
   cat <<\EOF
 
@@ -665,8 +665,8 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.52.20141204
-generated by GNU Autoconf 2.52.20141204
+GNU Autoconf configure 2.52.20150926
+generated by GNU Autoconf 2.52.20150926
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 Free Software Foundation, Inc.
@@ -680,8 +680,8 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52.20141204, which was
-generated by GNU Autoconf 2.52.20141204.  Invocation command line was
+It was created by GNU Autoconf $as_me 2.52.20150926, which was
+generated by GNU Autoconf 2.52.20150926.  Invocation command line was
 
   $ $0 $@
 
@@ -1106,7 +1106,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.52.20141204
+VERSION=2.52.20150926
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1112: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1718,8 +1718,8 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52.20141204
-configured by $0, generated by GNU Autoconf 2.52.20141204,
+GNU Autoconf config.status 2.52.20150926
+configured by $0, generated by GNU Autoconf 2.52.20150926,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -1801,7 +1801,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.52.20141204) 2.52.20141204, executed with
+This file was extended by $as_me (GNU Autoconf 2.52.20150926) 2.52.20150926, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1953,10 +1953,28 @@ EOF
       # These are the two extra sed commands mentioned above.
       (echo ':t
   /@[a-zA-Z_][a-zA-Z_0-9]*@/!b' && cat $tmp/subs.frag) >$tmp/subs-$ac_sed_frag.sed
+      # It is possible to make a multiline substitution using escaped newlines.
+      # Ensure that we do not split the substitution between script fragments.
+      ac_BEG=$ac_end
+      ac_END=`expr $ac_end + $ac_max_sed_lines`
+      sed "1,${ac_BEG}d; ${ac_END}p; q" $tmp/subs.sed >$tmp/subs.next
+      if test -s $tmp/subs.next; then
+        grep '^s,@[^@,][^@,]*@,.*\\$' $tmp/subs.next >$tmp/subs.edit
+        if test ! -s $tmp/subs.edit; then
+          grep "^s,@[^@,][^@,]*@,.*,;t t$" $tmp/subs.next >$tmp/subs.edit
+          if test ! -s $tmp/subs.edit; then
+            if test $ac_beg -gt 1; then
+              ac_end=`expr $ac_end - 1`
+              continue
+            fi
+          fi
+        fi
+      fi
+
       if test -z "$ac_sed_cmds"; then
-  	ac_sed_cmds="sed -f $tmp/subs-$ac_sed_frag.sed"
+        ac_sed_cmds="sed -f $tmp/subs-$ac_sed_frag.sed"
       else
-  	ac_sed_cmds="$ac_sed_cmds | sed -f $tmp/subs-$ac_sed_frag.sed"
+        ac_sed_cmds="$ac_sed_cmds | sed -f $tmp/subs-$ac_sed_frag.sed"
       fi
       ac_sed_frag=`expr $ac_sed_frag + 1`
       ac_beg=$ac_end
@@ -2039,7 +2057,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2042: creating $ac_file" >&5
+    { echo "$as_me:2060: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2057,7 +2075,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2060: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2078: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2070,7 +2088,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2073: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2091: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2086,7 +2104,7 @@ cat >>$CONFIG_STATUS <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' $ac_item`
         if test -z "$ac_used"; then
-          { echo "$as_me:2089: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:2107: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -2095,7 +2113,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' $ac_item`
       if test -n "$ac_seen"; then
-        { echo "$as_me:2098: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:2116: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -2132,7 +2150,7 @@ s,@INSTALL@,$ac_INSTALL,;t t
             ac_init=`egrep '[ 	]*'$ac_name'[ 	]*=' $ac_file`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'$ac_file':,'`
-              { echo "$as_me:2135: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:2153: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -2143,7 +2161,7 @@ $ac_seen" >&2;}
     egrep -n '@[A-Z_][A-Z_0-9]+@' $ac_file >>$tmp/out
     if test -s $tmp/out; then
       ac_seen=`sed -e 's,^,'$ac_file':,' < $tmp/out`
-      { echo "$as_me:2146: WARNING: Some variables may not be substituted:
+      { echo "$as_me:2164: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -2182,7 +2200,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.52.20141204 in
+case 2.52.20150926 in
   *[a-z]*)
     cat <<EOF
 
