snapshot of project "autoconf-252", label t20200802

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20200111 for GNU Autoconf 2.52.20200111.
+# Generated by Autoconf 2.52.20200802 for GNU Autoconf 2.52.20200802.
 #
 # Report bugs to <dickey@invisible-island.net>.
 #
@@ -151,8 +151,8 @@ mandir='${datarootdir}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52.20200111'
-PACKAGE_STRING='GNU Autoconf 2.52.20200111'
+PACKAGE_VERSION='2.52.20200802'
+PACKAGE_STRING='GNU Autoconf 2.52.20200802'
 PACKAGE_BUGREPORT='dickey@invisible-island.net'
 
 ac_prev=
@@ -565,7 +565,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.52.20200111 to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52.20200802 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -629,7 +629,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20200111:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20200802:";;
    esac
   cat <<\EOF
 
@@ -676,8 +676,8 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.52.20200111
-generated by GNU Autoconf 2.52.20200111
+GNU Autoconf configure 2.52.20200802
+generated by GNU Autoconf 2.52.20200802
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 Free Software Foundation, Inc.
@@ -691,8 +691,8 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52.20200111, which was
-generated by GNU Autoconf 2.52.20200111.  Invocation command line was
+It was created by GNU Autoconf $as_me 2.52.20200802, which was
+generated by GNU Autoconf 2.52.20200802.  Invocation command line was
 
   $ $0 $@
 
@@ -1117,7 +1117,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.52.20200111
+VERSION=2.52.20200802
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1123: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1631,6 +1631,8 @@ debug=false
 SHELL=\${CONFIG_SHELL-$SHELL}
 ac_cs_invocation="\$0 \$@"
 
+CLICOLOR_FORCE= GREP_OPTIONS=
+unset CLICOLOR_FORCE GREP_OPTIONS
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -1741,8 +1743,8 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52.20200111
-configured by $0, generated by GNU Autoconf 2.52.20200111,
+GNU Autoconf config.status 2.52.20200802
+configured by $0, generated by GNU Autoconf 2.52.20200802,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -1786,7 +1788,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1789: error: ambiguous option: $1
+    { { echo "$as_me:1791: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1805,7 +1807,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1808: error: unrecognized option: $1
+  -*) { { echo "$as_me:1810: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1824,7 +1826,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.52.20200111) 2.52.20200111, executed with
+This file was extended by $as_me (GNU Autoconf 2.52.20200802) 2.52.20200802, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1847,7 +1849,7 @@ do
   "config/Makefile" ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-  *) { { echo "$as_me:1850: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1852: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2081,7 +2083,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2084: creating $ac_file" >&5
+    { echo "$as_me:2086: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2099,7 +2101,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2102: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2104: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2112,7 +2114,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2115: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2117: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2128,7 +2130,7 @@ cat >>$CONFIG_STATUS <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' $ac_item`
         if test -z "$ac_used"; then
-          { echo "$as_me:2131: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:2133: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -2137,7 +2139,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' $ac_item`
       if test -n "$ac_seen"; then
-        { echo "$as_me:2140: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:2142: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -2174,7 +2176,7 @@ s,@INSTALL@,$ac_INSTALL,;t t
             ac_init=`egrep '[ 	]*'$ac_name'[ 	]*=' $ac_file`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'$ac_file':,'`
-              { echo "$as_me:2177: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:2179: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -2185,7 +2187,7 @@ $ac_seen" >&2;}
     egrep -n '@[A-Z_][A-Z_0-9]+@' $ac_file >>$tmp/out
     if test -s $tmp/out; then
       ac_seen=`sed -e 's,^,'$ac_file':,' < $tmp/out`
-      { echo "$as_me:2188: WARNING: Some variables may not be substituted:
+      { echo "$as_me:2190: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -2224,7 +2226,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.52.20200111 in
+case 2.52.20200802 in
   *[a-z]*)
     cat <<EOF
 
