snapshot of project "autoconf-252", label t20100930b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20100930 for GNU Autoconf 2.52.20100930.
+# Generated by Autoconf 2.52.20101001 for GNU Autoconf 2.52.20101001.
 #
 # Report bugs to <dickey@invisible-island.net>.
 #
@@ -149,8 +149,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='GNU Autoconf'
 PACKAGE_TARNAME='autoconf'
-PACKAGE_VERSION='2.52.20100930'
-PACKAGE_STRING='GNU Autoconf 2.52.20100930'
+PACKAGE_VERSION='2.52.20101001'
+PACKAGE_STRING='GNU Autoconf 2.52.20101001'
 PACKAGE_BUGREPORT='dickey@invisible-island.net'
 
 ac_prev=
@@ -547,7 +547,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures GNU Autoconf 2.52.20100930 to adapt to many kinds of systems.
+\`configure' configures GNU Autoconf 2.52.20101001 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -609,7 +609,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20100930:";;
+     short | recursive ) echo "Configuration of GNU Autoconf 2.52.20101001:";;
    esac
   cat <<\EOF
 
@@ -656,8 +656,8 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-GNU Autoconf configure 2.52.20100930
-generated by GNU Autoconf 2.52.20100930
+GNU Autoconf configure 2.52.20101001
+generated by GNU Autoconf 2.52.20101001
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 Free Software Foundation, Inc.
@@ -671,8 +671,8 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by GNU Autoconf $as_me 2.52.20100930, which was
-generated by GNU Autoconf 2.52.20100930.  Invocation command line was
+It was created by GNU Autoconf $as_me 2.52.20101001, which was
+generated by GNU Autoconf 2.52.20101001.  Invocation command line was
 
   $ $0 $@
 
@@ -1097,7 +1097,7 @@ fi
 
 PACKAGE=autoconf
 
-VERSION=2.52.20100930
+VERSION=2.52.20101001
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1103: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -1421,31 +1421,36 @@ do
 set dummy $ac_prog; ac_word=$2
 echo "$as_me:1422: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_INSTALL_INFO+set}" = set; then
+if test "${ac_cv_path_INSTALL_INFO+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$INSTALL_INFO"; then
-  ac_cv_prog_INSTALL_INFO="$INSTALL_INFO" # Let the user override the test.
-else
+  case $INSTALL_INFO in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_INSTALL_INFO="$INSTALL_INFO" # Let the user override the test with a path.
+  ;;
+  *)
   ac_save_IFS=$IFS; IFS=$ac_path_separator
-ac_dummy="$PATH"
+ac_dummy="$PATH:/sbin:/usr/sbin"
 for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
-  $as_executable_p "$ac_dir/$ac_word" || continue
-ac_cv_prog_INSTALL_INFO="$ac_prog"
-echo "$as_me:1437: found $ac_dir/$ac_word" >&5
-break
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_INSTALL_INFO="$ac_dir/$ac_word"
+   echo "$as_me:1439: found $ac_dir/$ac_word" >&5
+   break
+fi
 done
 
+  ;;
+esac
 fi
-fi
-INSTALL_INFO=$ac_cv_prog_INSTALL_INFO
+INSTALL_INFO=$ac_cv_path_INSTALL_INFO
+
 if test -n "$INSTALL_INFO"; then
-  echo "$as_me:1445: result: $INSTALL_INFO" >&5
+  echo "$as_me:1450: result: $INSTALL_INFO" >&5
 echo "${ECHO_T}$INSTALL_INFO" >&6
 else
-  echo "$as_me:1448: result: no" >&5
+  echo "$as_me:1453: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1458,7 +1463,7 @@ if test "$INSTALL_INFO" != no; then
 	 ( $INSTALL_INFO --version | fgrep -i -v debian ) >/dev/null 2>&1; then
      :
   else
-    { echo "$as_me:1461: WARNING: install-info utility not found" >&5
+    { echo "$as_me:1466: WARNING: install-info utility not found" >&5
 echo "$as_me: WARNING: install-info utility not found" >&2;}
 	INSTALL_INFO=no
   fi
@@ -1466,6 +1471,9 @@ fi
 
 # Automake can't see inner AC_SUBSTS (`aclocal' is bypassed), so we tag the
 # AC_SUBSTS here too.
+
+# Provide a properly-escaped bug-report address for the perl scripts.
+PACKAGE_BUGREPORT_PL=`echo "$PACKAGE_BUGREPORT" | sed -e 's/@/\\\\\\\\@/g'`
 
 ac_config_files="$ac_config_files Makefile m4/Makefile man/Makefile doc/Makefile config/Makefile tests/Makefile tests/atconfig"
 
@@ -1578,7 +1586,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1581: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1589: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1701,8 +1709,8 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-GNU Autoconf config.status 2.52.20100930
-configured by $0, generated by GNU Autoconf 2.52.20100930,
+GNU Autoconf config.status 2.52.20101001
+configured by $0, generated by GNU Autoconf 2.52.20101001,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -1746,7 +1754,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1749: error: ambiguous option: $1
+    { { echo "$as_me:1757: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1765,7 +1773,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1768: error: unrecognized option: $1
+  -*) { { echo "$as_me:1776: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1784,7 +1792,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (GNU Autoconf 2.52.20100930) 2.52.20100930, executed with
+This file was extended by $as_me (GNU Autoconf 2.52.20101001) 2.52.20101001, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1807,7 +1815,7 @@ do
   "config/Makefile" ) CONFIG_FILES="$CONFIG_FILES config/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/atconfig" ) CONFIG_FILES="$CONFIG_FILES tests/atconfig" ;;
-  *) { { echo "$as_me:1810: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1818: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1906,6 +1914,7 @@ s,@HELP2MAN@,$HELP2MAN,;t t
 s,@PERL@,$PERL,;t t
 s,@PERLSCRIPTS@,$PERLSCRIPTS,;t t
 s,@INSTALL_INFO@,$INSTALL_INFO,;t t
+s,@PACKAGE_BUGREPORT_PL@,$PACKAGE_BUGREPORT_PL,;t t
 CEOF
 
 EOF
@@ -2020,7 +2029,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2023: creating $ac_file" >&5
+    { echo "$as_me:2032: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2038,7 +2047,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2041: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2050: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2051,7 +2060,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2054: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2063: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -2107,7 +2116,7 @@ if test "$no_create" != yes; then
 fi
 
 # Report the state of this version of Autoconf if this is a beta.
-case 2.52.20100930 in
+case 2.52.20101001 in
   *[a-z]*)
     cat <<EOF
 
